apiVersion: v1
kind: Service
metadata: 
  name: obj-detection
  namespace: ecrp
spec: 
  ports: 
    - port: 5000
      protocol: UDP
      targetPort: 5000
      nodePort: 30500
  selector: 
    name: obj-detection
  type: NodePort
